# -*- coding: utf-8 -*-
"""svm_bayes_disaster_tweets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uA9wRvH0Q3fbuVjrJNi7mizjDFXdjBAG

# SVM & Bayes for Disaster Tweet Classification

This notebook implements a machine learning pipeline for classifying whether a tweet refers to a real disaster event.

The task is based on the Kaggle **NLP Getting Started** dataset. The goal is to preprocess tweet text, transform it into TF-IDF features, train SVM-based classifiers and Gaussian Naive Bayes, and compare their performance using multiple classification metrics.

## 1. Imports and Dataset Upload

The dataset is uploaded directly in Google Colab.  
The main file used for training and evaluation is `train.csv`, which contains the target labels.
"""

from google.colab import files
uploaded = files.upload()

import re
import string
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC, SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

from scipy import sparse

df = pd.read_csv("train.csv")

print("Dataset shape:", df.shape)
display(df.head())
display(df.info())
display(df.describe(include="all"))

"""## 2. Train/Test Split and Target Distribution

The dataset is split into train and test sets using a 90-10 ratio.  
Stratification is applied so that both subsets preserve approximately the same class distribution as the original dataset.
"""

train_df, test_df = train_test_split(df,test_size=0.10,random_state=0,stratify=df["target"])


print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

train_df["target"].value_counts().sort_index().plot(kind="bar", ax=axes[0])
axes[0].set_title("Target Distribution - Train Set")
axes[0].set_xlabel("Target")
axes[0].set_ylabel("Count")
axes[0].set_xticklabels(["Not Disaster", "Disaster"], rotation=0)

test_df["target"].value_counts().sort_index().plot(kind="bar", ax=axes[1])
axes[1].set_title("Target Distribution - Test Set")
axes[1].set_xlabel("Target")
axes[1].set_ylabel("Count")
axes[1].set_xticklabels(["Not Disaster", "Disaster"], rotation=0)

plt.tight_layout()
plt.show()

display(pd.DataFrame({
    "Train Count": train_df["target"].value_counts().sort_index(),
    "Train Percentage (%)": train_df["target"].value_counts(normalize=True).sort_index() * 100,
    "Test Count": test_df["target"].value_counts().sort_index(),
    "Test Percentage (%)": test_df["target"].value_counts(normalize=True).sort_index() * 100
}))

"""The dataset is not perfectly balanced, because the non-disaster class is more frequent than the disaster class.  
However, the imbalance is moderate and not extreme. For this reason, accuracy is useful, but F1-score, precision and recall are also important for evaluating the model more completely.

## 3. Text Preprocessing

The columns `id` and `location` are removed because they are not useful for textual classification in this task.  
Missing values in `keyword` are replaced with the string `null`, and then `keyword` and `text` are combined into a single input field.

The text cleaning pipeline applies the following steps:

- URL removal: removes links that usually do not contain useful linguistic information.
- HTML entity removal: removes encoded web symbols.
- Mention removal: removes Twitter usernames.
- Hashtag symbol removal: keeps the word but removes the `#` symbol.
- Unicode/emoji removal: removes noisy non-ASCII characters.
- Punctuation removal: removes symbols that usually increase vocabulary sparsity.
- Number removal: removes numeric tokens.
- Lowercasing: converts all text to lowercase.
- Whitespace normalization: removes extra spaces.
"""

def prepare_dataframe(data):
    data = data.copy()
    data = data.drop(columns=["id", "location"], errors="ignore")
    data["keyword"] = data["keyword"].fillna("null")
    data["inputs"] = data["keyword"].astype(str) + " " + data["text"].astype(str)
    return data

train_df_processed = prepare_dataframe(train_df)
test_df_processed = prepare_dataframe(test_df)

display(train_df_processed.head())

def clean_text(text):
    text = str(text)
    text = re.sub(r"http\S+|www\S+|https\S+", " ", text)
    text = re.sub(r"&\w+;", " ", text)
    text = re.sub(r"@\w+", " ", text)
    text = text.replace("#", "")
    text = text.encode("ascii", "ignore").decode("ascii")
    text = text.translate(str.maketrans("", "", string.punctuation))
    text = re.sub(r"\d+", " ", text)
    text = text.lower()
    text = re.sub(r"\s+", " ", text).strip()
    return text

train_df_processed["clean_inputs"] = train_df_processed["inputs"].apply(clean_text)
test_df_processed["clean_inputs"] = test_df_processed["inputs"].apply(clean_text)

display(train_df_processed[["inputs", "clean_inputs", "target"]].head())

"""## 4. Inputs and Targets

The cleaned tweet text is used as input, while the target is the binary disaster label.
"""

x_train_text = train_df_processed["clean_inputs"].values
y_train = train_df_processed["target"].values

x_test_text = test_df_processed["clean_inputs"].values
y_test = test_df_processed["target"].values

print("x_train:", x_train_text.shape)
print("y_train:", y_train.shape)
print("x_test:", x_test_text.shape)
print("y_test:", y_test.shape)

"""## 5. TF-IDF Vectorization

TF-IDF transforms each tweet into a numerical vector based on word importance.  
The vectorizer is fitted only on the training set using `fit_transform`, while the test set is transformed using only `transform`.

This avoids data leakage, because information from the test set must not influence the learned vocabulary or IDF weights.
"""

vectorizer = TfidfVectorizer(
    max_features=3000,
    ngram_range=(1, 2),
    min_df=2
)

x_train_tfidf = vectorizer.fit_transform(x_train_text)
x_test_tfidf = vectorizer.transform(x_test_text)

print("TF-IDF train shape:", x_train_tfidf.shape)
print("TF-IDF test shape:", x_test_tfidf.shape)

"""## 6. Linear SVM Classifier

A Linear Support Vector Classifier is trained on the TF-IDF vectors.  
Linear SVM is a strong baseline for text classification because TF-IDF data are usually high-dimensional and sparse.
"""

def evaluate_model(model_name, model, x_train, y_train, x_test, y_test):
    train_pred = model.predict(x_train)
    test_pred = model.predict(x_test)

    results = {
        "model": model_name,
        "train_accuracy": accuracy_score(y_train, train_pred),
        "train_precision": precision_score(y_train, train_pred, zero_division=0),
        "train_recall": recall_score(y_train, train_pred, zero_division=0),
        "train_f1": f1_score(y_train, train_pred, zero_division=0),
        "test_accuracy": accuracy_score(y_test, test_pred),
        "test_precision": precision_score(y_test, test_pred, zero_division=0),
        "test_recall": recall_score(y_test, test_pred, zero_division=0),
        "test_f1": f1_score(y_test, test_pred, zero_division=0)
    }

    print(model_name)
    print(classification_report(y_test, test_pred, zero_division=0))

    return results

results = []

linear_svc = LinearSVC(random_state=0)
linear_svc.fit(x_train_tfidf, y_train)

results.append(
    evaluate_model(
        "LinearSVC TF-IDF",
        linear_svc,
        x_train_tfidf,
        y_train,
        x_test_tfidf,
        y_test
    )
)

results_df = pd.DataFrame(results)
display(results_df)

"""For this application, recall for the disaster class is especially important because missing a real disaster tweet may delay an emergency response.  
However, precision is also important because false alarms could lead to unnecessary alerts. F1-score is a useful overall metric because it balances precision and recall.

## 7. PCA with 95% Explained Variance

PCA is applied after converting the TF-IDF matrices to dense arrays.  
The parameter `n_components=0.95` means that PCA keeps enough components to preserve 95% of the variance, not 95% of the original number of features.

The PCA transformation is fitted only on the training set and then applied to the test set.
"""

x_train_dense = x_train_tfidf.toarray()
x_test_dense = x_test_tfidf.toarray()

pca = PCA(n_components=0.95, random_state=0)
x_train_pca = pca.fit_transform(x_train_dense)
x_test_pca = pca.transform(x_test_dense)

print("Original TF-IDF features:", x_train_dense.shape[1])
print("PCA features:", x_train_pca.shape[1])
print("Explained variance ratio sum:", pca.explained_variance_ratio_.sum())

linear_svc_pca = LinearSVC(random_state=0)
linear_svc_pca.fit(x_train_pca, y_train)

results.append(
    evaluate_model(
        "LinearSVC PCA",
        linear_svc_pca,
        x_train_pca,
        y_train,
        x_test_pca,
        y_test
    )
)

svc_rbf_scale = SVC(kernel="rbf", gamma="scale", random_state=0)
svc_rbf_scale.fit(x_train_pca, y_train)

results.append(
    evaluate_model(
        "SVC RBF PCA gamma=scale",
        svc_rbf_scale,
        x_train_pca,
        y_train,
        x_test_pca,
        y_test
    )
)

"""## 8. Gamma: scale vs auto

For `SVC`, the default value is `gamma='scale'`.

- `scale`: gamma is calculated as `1 / (n_features * X.var())`.
- `auto`: gamma is calculated as `1 / n_features`.

The `scale` option adapts to the variance of the data, while `auto` only depends on the number of features.
"""

gamma_scale_value = 1 / (x_train_pca.shape[1] * x_train_pca.var())
gamma_auto_value = 1 / x_train_pca.shape[1]

print("Gamma value for scale:", gamma_scale_value)
print("Gamma value for auto:", gamma_auto_value)

svc_rbf_auto = SVC(kernel="rbf", gamma="auto", random_state=0)
svc_rbf_auto.fit(x_train_pca, y_train)

results.append(
    evaluate_model(
        "SVC RBF PCA gamma=auto",
        svc_rbf_auto,
        x_train_pca,
        y_train,
        x_test_pca,
        y_test
    )
)

"""## 9. Gaussian Naive Bayes

Gaussian Naive Bayes is trained on the original TF-IDF representation before PCA.  
Since `GaussianNB` requires dense input, the TF-IDF matrices are converted to dense arrays.
"""

gnb = GaussianNB()
gnb.fit(x_train_dense, y_train)

results.append(
    evaluate_model(
        "GaussianNB TF-IDF",
        gnb,
        x_train_dense,
        y_train,
        x_test_dense,
        y_test
    )
)

results_df = pd.DataFrame(results)
display(results_df)

"""## 10. Model Comparison

The following plot compares the test performance of all trained models using accuracy, F1-score, precision and recall.
"""

comparison_df = results_df[[
    "model",
    "test_accuracy",
    "test_f1",
    "test_precision",
    "test_recall"
]].copy()

display(comparison_df)

plot_df = comparison_df.set_index("model")

plt.figure(figsize=(14, 6))
plot_df.plot(kind="bar", figsize=(14, 6))
plt.title("Model Comparison on Test Set")
plt.xlabel("Model")
plt.ylabel("Score")
plt.xticks(rotation=45, ha="right")
plt.ylim(0, 1)
plt.legend(["Accuracy", "F1", "Precision", "Recall"])
plt.tight_layout()
plt.show()

"""## 11. Optional: Predictions for Kaggle Test File

The official Kaggle `test.csv` file does not contain target labels.  
This section can be used to generate predictions for submission using the best selected model trained on the internal training set.
"""

try:
    uploaded = files.upload()
    kaggle_test = pd.read_csv("test.csv")

    kaggle_test_processed = prepare_dataframe(kaggle_test)
    kaggle_test_processed["clean_inputs"] = kaggle_test_processed["inputs"].apply(clean_text)

    kaggle_test_tfidf = vectorizer.transform(kaggle_test_processed["clean_inputs"].values)
    kaggle_predictions = linear_svc.predict(kaggle_test_tfidf)

    submission = pd.DataFrame({
        "id": kaggle_test["id"],
        "target": kaggle_predictions
    })

    display(submission.head())
    submission.to_csv("submission.csv", index=False)
    files.download("submission.csv")
except Exception as e:
    print("Optional submission step skipped or failed:", e)

"""## Conclusion

This project compared SVM-based classifiers and Gaussian Naive Bayes for disaster tweet classification.  
TF-IDF was used to transform text into numerical features, while PCA was applied to reduce dimensionality while preserving 95% of the useful variance.

For emergency detection systems, F1-score and recall are especially important because the model should avoid missing real disaster-related posts, while still limiting false alarms.
"""